# Generated by Django 4.2.1 on 2024-02-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
    ]
